import { Be_Vietnam_Pro, Geist } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import { DynaPuff } from "next/font/google";
import { NTR } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dynaPuff = DynaPuff({
  variable: "--font-dynapuff",
  weight: ['400', '700'],
  subsets: ["latin"],
});

const ntr = NTR({
  variable: "--font-ntr",
  weight: ['400'],
  subsets: ["latin"],
});

const robo = Roboto({
  variable: "--font-roboto",
  weight: ['100', '900'],
  subsets: ["latin"],
});

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  weight: ['300', '400', '700'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Maloudnee Marcier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dynaPuff.variable} ${ntr.variable} ${robo.variable} ${beVietnamPro.variable} antialiased pt-14`}
      >
        {children}
        <NavBar />
      </body>
    </html>
  );
}